// ==============================================================================
// FILE: MasterBuilder.scad
// ARCHITECTURE: Layer 4 (User Interface & Main Entry Point)
// PURPOSE: Customizer-friendly UI + build dispatcher for MasterTray system
// ==============================================================================
/* [Printer / Slicer Setting] */
Nozzle_Diameter = 0.4;  // [0.2, 0.4, 0.6, 0.8]
Wall_Loops      = 2;    // [1 : 1 : 10]
Layer_Height    = 0.28; // [0.12, 0.16, 0.20, 0.24, 0.28]
Filament_Type   = "PLA"; // ["PLA", "PETG", "TPU", "ABS"]
Mechanical_Fit  = "Standard"; // ["Tighter", "Tight", "Standard", "Loose", "Looser"]

/* [Build Selection] */
Part_To_Build = "Box"; // ["Box", "Pillbox Full Set", "Lid", "Simple Tray", "Jar", "Threaded Jar", "S4 Jar", "Spool Jar", "S4 Wedge", "S4 Set", "Plaque", "Grid", "Grid Test", "Lid Testing"]

/* [Dimensions: W x L x H] */
part_width  = 40;   // [10 : 0.5 : 300]
part_length = 80;   // [10 : 0.5 : 300]
part_height = 30;   // [5 : 0.5 : 300]
dimension_mode = "Total"; // ["Total", "Usable"]
// Grid layout string — leave blank for no grid. When non-empty, container intents
// auto-generate all variants: plain + built-in grid + drop-in (no base) + drop-in
// (with base). The "Grid" intent emits only the two rectangular drop-in variants.
// Jar grids are generated by jar intents only (circular clip is meaningful there).
// Total mode: LWH are outer container dims; drop-in is sized to fit snugly inside.
// Usable mode: LWH are interior dims; drop-in is sized to those dims minus tolerance.
grid_layout = "(A1,60,0)(A2,60,145,80%)(A3,60,195,C40,80)[A1,N][A2,E][A3,E]";

/* [Box Lid Types] */
// Each checked type generates an additional box+lid pair on the platter.
Snap_External = true;
Snap_Internal = true;
Glide_External = true;
Glide_Internal = true;
Glide_Direction = "H"; // ["H", "V"]
Glide_Snap      = "Ball"; // ["Ball", "Tab"]
Flip_Single = true;
Flip_Double = true;

/* [Stacking Trays] */
// When building "Simple Tray", also generate these stackable variants.
Nesting = true;
Peg     = true;

/* [Jar] */
jar_shape = "Circle"; // ["Circle", "Quad", "Hexa", "Octa", "Dodeca"]
// Yes = threaded jar + screw lid.  No = open-top jar, no lid.
Jar_Lid = false;

/* [Mesh Aesthetics] */
mesh_pattern = "Teardrop"; // ["Honeycomb", "Teardrop", "Slotted", "Circle", "Square", "Diamond", "None"]
// Hole diameter (mm). Min printable ≈ 1.0mm at 0.4mm nozzle.
mesh_hole_size = 1.6; // [0.5 : 0.1 : 8.0]
// Minimum gap between hole edges (mm). Physics floor always applies regardless.
// Tip: Wall_Loops × Nozzle_Diameter (e.g. 2 × 0.4 = 0.8mm at default settings).
mesh_hole_spacing = 1.2; // [1.0 : 0.1 : 5.0]
// Solid border as % of surface. 0 = edge-to-edge holes. 100 = fully solid (no mesh).
// The minimum solid margin at the jar neck / box lip is provided by the container
// geometry itself — the mesh strut% is purely aesthetic and always honoured as-is.
strut_wall_perc  =  0; // [0 : 5 : 100]
strut_floor_perc = 25; // [0 : 5 : 100]
strut_lid_perc   = 75; // [0 : 5 : 100]

/* [Wall Modifications] */
modify_wall = "None"; // ["None", "Dropped", "50%", "25%"]
target_wall = "All Walls"; // ["All Walls", "Front", "Back", "Left", "Right"]

/* [Plaque / Labels] */
// "Wall"    = U-Clip + swivel face plate (for tray/box wall edges).
// "Lid"     = face plate only, flat back — adhesive-mount on any flat lid surface.
// "Lid_Peg" = face plate with two press-fit pegs on the back — snaps into lid holes.
plaque_target = "Wall"; // ["Wall", "Lid", "Lid_Peg"]
// Wall only: "Vertical" = clip grips thin dropped-wall vertical edge.
//            "Horizontal" = clip straddles horizontal top rim of any wall or box.
clip_type  = "Vertical"; // ["Vertical", "Horizontal"]
// Face plate width (mm). Set to match your label stock.
plaque_w   = 50; // [20 : 5 : 120]
// Face plate height (mm). Set to match your label stock.
plaque_h   = 40; // [15 : 5 : 100]
// Wall only: clip body height (mm) — should span the wall section it grips.
clip_h     = 20; // [10 : 5 : 60]

/* [Core Engineering (R&D Exposed)] */
floor_thickness = 2.0;
lid_thickness = 2.0;
wall_thickness = 2.4;
divider_thickness = 1.2;
peg_thickness_multiplier = 2.0;
platter_gap = 15;
thread_pitch = 2.0;

/* [High-Peg Mod] */
stackable_peg_height = 80; // [20 : 10 : 200]

/* [Advanced - Geometry Overrides] */
// 0 = auto-computed from printer settings. Non-zero = explicit override.
// corner_radius: rounds the physical 3D corners of the container body (mm).
// Corner_Round_Ratio: rounds mesh hole corners as a fraction of the hole diameter —
//   completely separate from corner_radius. 0.05=near-square, 0.45=near-circle.
//   Only affects square/slotted holes >~2.1mm; below that Arachne floor takes over.
corner_radius       = 0.0; // [0 : 0.1 : 10.0]
Corner_Round_Ratio  = 0.20; // [0.05:0.05:0.45]
chamfer_size        = 0.4; // [0 : 0.1 : 3.0]
peg_socket_diameter = 8.0; // [4 : 0.5 : 16.0]
nesting_ledge_depth = 2.0; // [1 : 0.5 : 8.0]
peg_protrusion      = 0.0; // [0 : 0.5 : 20.0] — builtin peg height above tray, 0=auto

/* [Advanced - Slicer Modifier Hints] */
// Emit bounding-volume bodies for hubs alongside drop-in grids.
// Import the STL, "split to objects" in the slicer, select the hint bodies, set as
// modifier, assign fine layer height / speed — no manual sizing or positioning needed.
// Turn off if the extra bodies cause any slicing issue.
grid_modifier_hints = true;

/* [Advanced - Debug] */
// Human-readable report to the console (View → Console after F5).
debug_report = false;
// Pipe-delimited payload for Perl + Template Toolkit report generation.
debug_payload = false;

/* [Advanced - Boolean Epsilon] */
// How far difference() cutters extend past the face they pierce (default 0.1mm).
// Prevents Z-fighting in F5 preview and non-manifold edges on export.
// Raise toward 0.2–0.3 if you see flickering cut faces. See LESSONS.md §EPS.
bool_overlap_eps = 0.1; // [0.01 : 0.01 : 0.5]

include <MasterManifest.scad>
include <MasterDebug.scad>

include <RenderTray.scad>
include <RenderPeg.scad>
include <RenderJar.scad>
include <RenderLid.scad>
include <RenderGrid.scad>
include <RenderBox.scad>
include <RenderPlaque.scad>

// Override MasterEngine defaults with Customizer values (must follow all includes).
EPS  = bool_overlap_eps;
EPS2 = EPS * 2;

// --- AUTO-MATH ENGINE ---
raw_w = (dimension_mode == "Usable") ? part_width + (wall_thickness * 2) : part_width;
raw_l = (dimension_mode == "Usable") ? part_length + (wall_thickness * 2) : part_length;
raw_h = (dimension_mode == "Usable") ? part_height + floor_thickness + lid_thickness : part_height;

ui_payload = [
    [BUILDER_VERSION,    "v4.26"], 
    ["FILAMENT_TYPE",    Filament_Type], 
    ["FIT_PROFILE",      Mechanical_Fit],
    [DIMENSION_MODE,     dimension_mode], 
    [WIDTH,              raw_w], 
    [LENGTH,             raw_l], 
    [HEIGHT,             raw_h],
    [PEG_HEIGHT,         stackable_peg_height], 
    [LAYER_HEIGHT,       Layer_Height], 
    [WALL_LOOPS,         Wall_Loops], 
    [NOZZLE_DIAMETER,    Nozzle_Diameter],
    [PATTERN,            mesh_pattern], 
    [HOLE_WALL,          mesh_hole_size],
    [HOLE_FLOOR,         mesh_hole_size],
    [HOLE_LID,           mesh_hole_size],
    [HOLE_SPACING,       mesh_hole_spacing],
    [STRUT_WALL,         strut_wall_perc], 
    [STRUT_FLOOR,        strut_floor_perc], 
    [STRUT_LID,          strut_lid_perc],
    [WALL_MODIFY,        modify_wall], 
    [WALL_TARGET,        target_wall], 
    [GRID_LAYOUT,        grid_layout],
    [PLAQUE_TARGET,      plaque_target],
    [CLIP_TYPE,          clip_type],
    [PLAQUE_W,           plaque_w],
    [PLAQUE_H,           plaque_h],
    [CLIP_H,             clip_h],
    [THICK_FLOOR,        floor_thickness], 
    [THICK_LID,          lid_thickness], 
    [THICK_WALL,         wall_thickness], 
    [THICK_DIVIDER,      divider_thickness],
    [THICK_PEG_MULT,     peg_thickness_multiplier], 
    [PLATTER_GAP,        platter_gap], 
    [THREAD_PITCH,       thread_pitch],
    [JAR_SHAPE,          jar_shape],
    [SNAP_EXTERNAL,      Snap_External],
    [SNAP_INTERNAL,      Snap_Internal],
    [GLIDE_EXTERNAL,     Glide_External],
    [GLIDE_INTERNAL,     Glide_Internal],
    [BUILD_FLIP_SINGLE,  Flip_Single],
    [BUILD_FLIP_DOUBLE,  Flip_Double],
    [STACK_NESTING,      Nesting],
    [STACK_PEG,          Peg],
    [JAR_WITH_LID,       Jar_Lid],
    [GLIDE_DIR,          Glide_Direction],
    [GLIDE_SNAP,         Glide_Snap],
    [CHAMFER_SIZE,       chamfer_size],
    [CORNER_RADIUS,      corner_radius],
    [PEG_SOCKET_D,       peg_socket_diameter],
    [LEDGE_DEPTH,        nesting_ledge_depth],
    [PEG_PROTRUSION,     peg_protrusion],
    [GRID_MOD_HINTS,     grid_modifier_hints]
];

// --- FACTORY DISPATCHER ---
module build_part(name, data) {
    manifest = compile_manifest(name, data);
    echo(str("Building: ", name, " (", len(manifest), " components)"));
    for (i = [0 : len(manifest) - 1]) {
        item    = manifest[i];
        type    = item[0];
        payload = item[1];
        options = item[2];
        physics = item[3];
        pos     = get_xy(manifest, i);
        translate([pos[0], pos[1], 0]) {
            if      (type == "TRAY")             { factory_render_tray(payload, options, physics); }
            else if (type == "BOX")              { factory_render_box(payload, options, physics); }
            else if (type == "FLIP_BOX")         { factory_render_flip_box(payload, options, physics); }
            else if (type == "DOUBLE_FLIP_BOX")  { factory_render_double_flip_box(payload, options, physics); }
            else if (type == "JAR")              { factory_render_jar(payload, options, physics); }
            else if (type == "LID")              { factory_render_lid(payload, options, physics); }
            else if (type == "GRID")             { factory_render_grid(payload, options, physics); }
            else if (type == "PEG")              { factory_render_peg(payload, options, physics); }
            else if (type == "PLAQUE")           { factory_render_plaque(payload, options, physics); }
            else { echo(str("WARNING: Unknown component type: ", type)); }
        }
    }
}

// --- FINAL EXECUTION ---
if (debug_report)  dump_build_options(Part_To_Build,  ui_payload);
if (debug_payload) dump_build_payload(Part_To_Build, ui_payload);
build_part(Part_To_Build, ui_payload);