// ==============================================================================
// FILE: MasterEnum.scad [v4.0]
// ARCHITECTURE: Layer 0 (The Lexicon & Dictionary)
// ==============================================================================

TYPE          = "TYPE"; WIDTH = "WIDTH"; LENGTH = "LENGTH"; HEIGHT = "HEIGHT";
DIMENSION_MODE= "DIMENSION_MODE"; 
BUILDER_VERSION = "BUILDER_VERSION"; 
LAYER_HEIGHT  = "LAYER_HEIGHT"; WALL_LOOPS = "WALL_LOOPS"; NOZZLE_DIAMETER = "NOZZLE_DIAMETER";
PATTERN       = "PATTERN"; HOLE_WALL = "HOLE_WALL"; HOLE_FLOOR = "HOLE_FLOOR"; HOLE_LID = "HOLE_LID";
STRUT_WALL    = "STRUT_WALL"; STRUT_FLOOR = "STRUT_FLOOR"; STRUT_LID = "STRUT_LID";      
GRID_LAYOUT   = "GRID_LAYOUT"; GRID_HAS_BASE = "GRID_HAS_BASE"; 
GRID_TYPE     = "GRID_TYPE"; 
PLAQUE_STYLE  = "PLAQUE_STYLE"; PLAQUE_TEXT = "PLAQUE_TEXT"; PLAQUE_TEXT_SIZE = "PLAQUE_TEXT_SIZE";
WALL_MODIFY   = "WALL_MODIFY"; WALL_TARGET = "WALL_TARGET";    
THICK_FLOOR   = "THICK_FLOOR"; THICK_LID = "THICK_LID"; THICK_WALL = "THICK_WALL"; THICK_DIVIDER = "THICK_DIVIDER";
LID_MIN_SOLID = "LID_MIN_SOLID"; THICK_PEG_MULT = "THICK_PEG_MULT"; 
TOL_SNAP_GAP  = "TOL_SNAP_GAP"; TOL_CLIP = "TOL_CLIP"; PLATTER_GAP = "PLATTER_GAP"; THREAD_PITCH = "THREAD_PITCH";
PEG_HEIGHT    = "PEG_HEIGHT"; 

HONEYCOMB = "Honeycomb"; TEARDROP = "Teardrop"; SLOTTED = "Slotted";
CIRCLE = "Circle"; SQUARE = "Square"; DIAMOND = "Diamond"; NONE = "None";

NEEDS_GROOVE = "NEEDS_GROOVE"; HAS_THREADS = "HAS_THREADS"; HAS_BUILTIN_GRID = "HAS_BUILTIN_GRID"; 

BOX = "BOX"; LID = "LID"; LID_GLIDE = "LID_GLIDE";     
TRAY_SIMPLE = "TRAY_SIMPLE"; 
TRAY_STACK_NEST = "TRAY_STACK_NEST"; 
TRAY_STACK_PEG = "TRAY_STACK_PEG";   
PEG = "PEG"; 

BOX_GRID = "BOX_GRID"; JAR_GRID = "JAR_GRID";
JAR = "JAR"; JAR_LID = "JAR_LID";
PLAQUE = "PLAQUE"; PLAQUE_JAR = "PLAQUE_JAR";
DESICCANT_BOX = "DESICCANT_BOX"; DESICCANT_LID = "DESICCANT_LID";

FLIP_BOX = "FLIP_BOX"; FLIP_LID = "FLIP_LID"; DOUBLE_FLIP_BOX = "DOUBLE_FLIP_BOX";