// ==============================================================================
// FILE: MasterBuilder.scad
// ARCHITECTURE: Layer 4 (User Interface & Main Entry Point)
// PURPOSE: Customizer-friendly UI + build dispatcher for MasterTray system
// ==============================================================================
// @CONFIG_SECTION_START: printer
/* [Printer / Slicer Setting] */
Nozzle_Diameter = 0.4;  // [0.2, 0.4, 0.6, 0.8]
Wall_Loops      = 2;    // [1 : 1 : 10]
Layer_Height    = 0.28; // [0.12, 0.16, 0.20, 0.24, 0.28]
Filament_Type   = "PLA"; // ["PLA", "PETG", "TPU", "ABS"]
Mechanical_Fit  = "Standard"; // ["Tighter", "Tight", "Standard", "Loose", "Looser"]
// @CONFIG_SECTION_END: printer

/* [Build Selection] */
Part_To_Build = "Box"; // ["Box", "Pillbox Full Set", "Lid", "Simple Tray", "Jar", "Threaded Jar", "S4 Jar", "Spool Jar", "S4 Wedge", "S4 Set", "Plaque", "Grid", "Grid Test", "Lid Testing"]

/* [Dimensions: W x L x H] */
part_width  = 140;  // [10 : 0.5 : 300]
part_length = 70;   // [10 : 0.5 : 300]
part_height = 20;   // [5 : 0.5 : 300]
dimension_mode = "Total"; // ["Total", "Usable"]
// Grid layout string — leave blank for no grid. When non-empty, container intents
// auto-generate all variants: plain + built-in grid + drop-in (no base) + drop-in
// (with base). The "Grid" intent emits only the two rectangular drop-in variants.
// Jar grids are generated by jar intents only (circular clip is meaningful there).
// Total mode: LWH are outer container dims; drop-in is sized to fit snugly inside.
// Usable mode: LWH are interior dims; drop-in is sized to those dims minus tolerance.
grid_layout = "(A1,60,0)(A2,60,145,80%)(A3,60,195,C40,80)[A1,N][A2,E][A3,E]";

/* [Box Lid Types] */
// Standalone "Lid" intent: select which lid type to build.
// Glide also uses Glide_Direction and Glide_Snap below.
// Snap also uses Lid_Style below.
Standalone_Lid_Type  = "Flip_Single"; // ["Slip", "Snap", "Glide", "Flip_Single", "Flip_Double", "Screw"]
Lid_Style            = "External";    // ["External", "Rabbet"]

// Each checked type generates an additional box+lid pair on the platter.
Snap_External = false;
Snap_Internal = false;
Glide_External = false;
Glide_Internal = false;
Glide_Direction = "H"; // ["H", "V"]
Glide_Snap      = "Ball"; // ["Ball", "Tab"]
Flip_Single = true;
Flip_Double = false;

/* [Stacking Trays] */
// When building "Simple Tray", also generate these stackable variants.
Nesting = true;
Peg     = true;

/* [Pillbox] */
// Compartment columns for the pillbox intents (7-Day Pill Box, 7-Day AM/PM Box,
// 1-Day AM/PM Box). Box width is divided into this many compartments.
Pillbox_Days = 7; // [1:7]

/* [Jar] */
jar_shape = "Circle"; // ["Circle", "Quad", "Hexa", "Octa", "Dodeca"]
// Yes = threaded jar + screw lid.  No = open-top jar, no lid.
Jar_Lid = false;

// @CONFIG_SECTION_START: mesh
/* [Mesh Aesthetics] */
mesh_pattern = "None"; // ["Honeycomb", "Teardrop", "Slotted", "Circle", "Square", "Diamond", "None"]
// Hole diameter (mm). Min printable ≈ 1.0mm at 0.4mm nozzle.
mesh_hole_size = 0; // [0.0 : 0.1 : 8.0]
// Minimum gap between hole edges (mm). Physics floor always applies regardless.
// Tip: Wall_Loops × Nozzle_Diameter (e.g. 2 × 0.4 = 0.8mm at default settings).
mesh_hole_spacing = 1.2; // [0.0: 0.1 : 5.0]
// Solid border as % of surface. 0 = edge-to-edge holes. 100 = fully solid (no mesh).
// The minimum solid margin at the jar neck / box lip is provided by the container
// geometry itself — the mesh strut% is purely aesthetic and always honoured as-is.
strut_wall_perc  =  0; // [0 : 5 : 100]
strut_floor_perc = 25; // [0 : 5 : 100]
strut_lid_perc   = 75; // [0 : 5 : 100]
// @CONFIG_SECTION_END: mesh

/* [Wall Modifications] */
modify_wall = "None"; // ["None", "Dropped", "50%", "25%"]
target_wall = "All Walls"; // ["All Walls", "Front", "Back", "Left", "Right"]

/* [Plaque / Labels] */
// "Wall"    = U-Clip + swivel face plate (for tray/box wall edges).
// "Lid"     = face plate only, flat back — adhesive-mount on any flat lid surface.
// "Lid_Peg" = face plate with two press-fit pegs on the back — snaps into lid holes.
plaque_target = "Wall"; // ["Wall", "Lid", "Lid_Peg"]
// Wall only: "Vertical" = clip grips thin dropped-wall vertical edge.
//            "Horizontal" = clip straddles horizontal top rim of any wall or box.
clip_type  = "Vertical"; // ["Vertical", "Horizontal"]
// Face plate width (mm). Set to match your label stock.
plaque_w   = 50; // [20 : 5 : 120]
// Face plate height (mm). Set to match your label stock.
plaque_h   = 40; // [15 : 5 : 100]
// Wall only: clip body height (mm) — should span the wall section it grips.
clip_h     = 20; // [10 : 5 : 60]

// @CONFIG_SECTION_START: advanced
/* [Core Engineering (R&D Exposed)] */
floor_thickness = 2.0;
lid_thickness = 2.0;
wall_thickness = 2.4;
divider_thickness = 1.2;
peg_thickness_multiplier = 2.0;
platter_gap = 15;
thread_pitch = 2.0;

/* [High-Peg Mod] */
stackable_peg_height = 80; // [20 : 10 : 200]

/* [Advanced - Geometry Overrides] */
// 0 = auto-computed from printer settings. Non-zero = explicit override.
// corner_radius: rounds the physical 3D corners of the container body (mm).
// Corner_Round_Ratio: rounds mesh hole corners as a fraction of the hole diameter —
//   completely separate from corner_radius. 0.05=near-square, 0.45=near-circle.
//   Only affects square/slotted holes >~2.1mm; below that Arachne floor takes over.
corner_radius       = 0.0; // [0 : 0.1 : 10.0]
Corner_Round_Ratio  = 0.20; // [0.05:0.05:0.45]
chamfer_size        = 0.4; // [0 : 0.1 : 3.0]
peg_socket_diameter = 8.0; // [4 : 0.5 : 16.0]
nesting_ledge_depth = 2.0; // [1 : 0.5 : 8.0]
peg_protrusion      = 0.0; // [0 : 0.5 : 20.0] — builtin peg height above tray, 0=auto

/* [Advanced - Slicer Modifier Hints] */
// Emit bounding-volume bodies for hubs alongside drop-in grids.
// Import the STL, "split to objects" in the slicer, select the hint bodies, set as
// modifier, assign fine layer height / speed — no manual sizing or positioning needed.
// Turn off if the extra bodies cause any slicing issue.
grid_modifier_hints = true;

/* [Advanced - Debug] */
// Human-readable report to the console (View → Console after F5).
debug_report = false;
// Pipe-delimited payload for Perl + Template Toolkit report generation.
debug_payload = false;

/* [Advanced - Boolean Epsilon] */
// How far difference() cutters extend past the face they pierce (default 0.1mm).
// Prevents Z-fighting in F5 preview and non-manifold edges on export.
// Raise toward 0.2–0.3 if you see flickering cut faces. See LESSONS.md §EPS.
bool_overlap_eps = 0.01; // [0.001 : 0.001 : 0.1]
// @CONFIG_SECTION_END: advanced

/* [Advanced - 2D Export (laser / CNC)] */
// When true, the whole model is sliced at Z=0 with projection(cut=true) to a flat
// 2D outline for laser-cut / CNC stock (e.g. a clear acrylic lid). Export to .svg
// or .dxf — NOT .stl (2D geometry can't be an STL). Drive from the CLI with:
//   mastertray.py build ... --export-2d svg
// Kept OUTSIDE the @CONFIG_SECTION blocks so it isn't part of the config-sync set.
Export_2D = false;

/* [Advanced - Modifier Export] */
// When true, emit ONLY the grid modifier-hint discs (no grid/box/lid geometry) as
// a standalone STL. Load it into the slicer alongside the normal model and set it
// as a modifier volume — no manual "split to objects" needed. Requires an intent
// with a grid layout that has circular hubs (C/S/D/T). Drive from the CLI with:
//   mastertray.py build --intent Grid ... --export-modifiers
Hints_Only = false;

// MasterEngine (and via it BOSL2, MasterEnum, MasterConstants) is included exactly
// ONCE here, as the first include, so the heavy BOSL2 library is parsed a single
// time. OpenSCAD does not deduplicate includes, so every redundant include re-parses
// BOSL2 — that was ~21s of fixed build overhead. The sub-files below NO LONGER
// include MasterEngine themselves; they rely on this single load. [perf]
//
// TRADEOFF (accepted): individual sub-files (RenderBox.scad, etc.) can no longer be
// opened standalone in the OpenSCAD GUI — they are only valid when built through
// MasterBuilder. Open MasterBuilder.scad to preview/debug any part instead.
include <MasterEngine.scad>

include <MasterManifest.scad>
include <MasterDebug.scad>

include <RenderTray.scad>
include <RenderPeg.scad>
include <RenderJar.scad>
include <RenderLid.scad>
include <RenderGrid.scad>
include <RenderBox.scad>
include <RenderPlaque.scad>

// Override MasterEngine defaults with Customizer values (must follow all includes).
EPS  = bool_overlap_eps;
LINE_W = Nozzle_Diameter;   // one line width — scales with printer; LINE_W/2 per cutter face

// --- AUTO-MATH ENGINE ---
raw_w = (dimension_mode == "Usable") ? part_width + (wall_thickness * 2) : part_width;
raw_l = (dimension_mode == "Usable") ? part_length + (wall_thickness * 2) : part_length;
raw_h = (dimension_mode == "Usable") ? part_height + floor_thickness + lid_thickness : part_height;

ui_payload = make_env(
    // Identity
    builder_version   = "v4.26",
    // Printer / slicer
    filament_type     = Filament_Type,
    fit_profile       = Mechanical_Fit,
    layer_height      = Layer_Height,
    wall_loops        = Wall_Loops,
    nozzle_diameter   = Nozzle_Diameter,
    // Dimensions
    dimension_mode    = dimension_mode,
    width             = raw_w,
    length            = raw_l,
    height            = raw_h,
    // Mesh
    pattern           = mesh_pattern,
    hole_wall         = mesh_hole_size,
    hole_floor        = mesh_hole_size,
    hole_lid          = mesh_hole_size,
    hole_spacing      = mesh_hole_spacing,
    strut_wall        = strut_wall_perc,
    strut_floor       = strut_floor_perc,
    strut_lid         = strut_lid_perc,
    // Geometry overrides
    chamfer_size      = chamfer_size,
    corner_radius     = corner_radius,
    // Thicknesses
    thick_floor       = floor_thickness,
    thick_lid         = lid_thickness,
    thick_wall        = wall_thickness,
    thick_divider     = divider_thickness,
    thick_peg_mult    = peg_thickness_multiplier,
    // Stacking
    peg_height        = stackable_peg_height,
    peg_socket_d      = peg_socket_diameter,
    ledge_depth       = nesting_ledge_depth,
    peg_protrusion    = peg_protrusion,
    // Layout / platter
    platter_gap       = platter_gap,
    grid_layout       = grid_layout,
    grid_mod_hints    = grid_modifier_hints,
    // Lid type selection (Box intent)
    snap_external     = Snap_External,
    snap_internal     = Snap_Internal,
    glide_external    = Glide_External,
    glide_internal    = Glide_Internal,
    build_flip_single = Flip_Single,
    build_flip_double = Flip_Double,
    glide_dir         = Glide_Direction,
    glide_snap        = Glide_Snap,
    // Lid type selection (Container Lid / standalone intent)
    lid_type_sel      = Standalone_Lid_Type,
    lid_style         = Lid_Style,
    // Simple Tray stacking variants
    stack_nesting     = Nesting,
    stack_peg         = Peg,
    // Jar
    jar_shape         = jar_shape,
    jar_with_lid      = Jar_Lid,
    thread_pitch      = thread_pitch,
    // Plaque / label
    plaque_target     = plaque_target,
    clip_type         = clip_type,
    plaque_w          = plaque_w,
    plaque_h          = plaque_h,
    clip_h            = clip_h,
    // Pillbox
    pillbox_days      = Pillbox_Days,
    // Wall modifications
    wall_modify       = modify_wall,
    wall_target       = target_wall
);

// --- FACTORY DISPATCHER ---
module build_part(name, data) {
    manifest = compile_manifest(name, data);
    echo(str("Building: ", name, " (", len(manifest), " components)"));
    for (i = [0 : len(manifest) - 1]) {
        item    = manifest[i];
        type    = item[0];
        payload = item[1];
        options = item[2];
        physics = item[3];
        pos     = get_xy(manifest, i);
        translate([pos[0], pos[1], 0]) {
            // Modifier-export mode (Hints_Only): only GRID components render, and the
            // grid factory emits just its marker discs (see factory_render_grid).
            if      (Hints_Only && type != "GRID") { /* skip non-grid in modifier export */ }
            else if (type == "TRAY")             { factory_render_tray(payload, options, physics); }
            else if (type == "BOX")              { factory_render_box(payload, options, physics); }
            else if (type == "FLIP_BOX")         { factory_render_flip_box(payload, options, physics); }
            else if (type == "DOUBLE_FLIP_BOX")  { factory_render_double_flip_box(payload, options, physics); }
            else if (type == "JAR")              { factory_render_jar(payload, options, physics); }
            else if (type == "LID") {
                if (get_val("ROTATE_180", options, false))
                    rotate([0, 0, 180]) factory_render_lid(payload, options, physics);
                else
                    factory_render_lid(payload, options, physics);
            }
            else if (type == "GRID")             { factory_render_grid(payload, options, physics); }
            else if (type == "PEG")              { factory_render_peg(payload, options, physics); }
            else if (type == "PLAQUE")           { factory_render_plaque(payload, options, physics); }
            else { assert(false, str("Unknown component type: ", type, " (manifest bug)")); }
        }
    }
}

// --- FINAL EXECUTION ---
if (debug_report)  dump_build_options(Part_To_Build,  ui_payload);
if (debug_payload) dump_build_payload(Part_To_Build, ui_payload);
// Export_2D wraps the build in projection(cut=true) for laser/CNC 2D output.
// Normal (3D/STL) builds keep Export_2D=false and are completely unaffected.
if (Export_2D) projection(cut=true) build_part(Part_To_Build, ui_payload);
else           build_part(Part_To_Build, ui_payload);